name: Deploy Hemi Webapp

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install Dependencies
        run: npm ci

      # Migrations must be manually run before deploying the portal
      - name: Run migrations
        run: npx lerna run deploy --scope=migrations-pg --since=${{ github.event.before }}
        env:
          DEPLOY_POSTGRES_CONNECTION_DATABASE: ${{ secrets.POSTGRES_CONNECTION_DATABASE }}
          DEPLOY_POSTGRES_CONNECTION_HOST: ${{ secrets.POSTGRES_CONNECTION_HOST }}
          DEPLOY_POSTGRES_CONNECTION_PASSWORD: ${{ secrets.POSTGRES_CONNECTION_PASSWORD }}
          DEPLOY_POSTGRES_CONNECTION_USER: ${{ secrets.POSTGRES_CONNECTION_USER }}
      
      # Deploy everything else, ignoring migrations
      - name: Build site
        run: npx lerna run deploy --ignore=migrations-pg --since=${{ github.event.before }} --concurrency=1
        env:
          # portal envs
          BASE_PATH: "/app-testnet"
          NEXT_PUBLIC_RECAPTCHA_SITE_KEY: $ {{ secrets.NEXT_PUBLIC_RECAPTCHA_SITE_KEY }} 
          NEXT_PUBLIC_CLAIM_TOKENS_URL: http://localhost:4000/dev # to be updated once claim-tokens service is deployed

      - name: Check portal build
        id: portal_build
        uses: andstor/file-existence-action@v3
        with:
          files: "./webapp/out/"

      - name: Copy portal files to Hostinger
        # folder should only exists if portal was built
        if: steps.portal_build.outputs.files_exists == 'true'
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USER }}
          port: ${{ secrets.HOSTINGER_PORT }}
          key: ${{ secrets.HOSTINGER_SSH_KEY }}
          source: webapp/out/*
          target: public_html/app-testnet
          rm: true
          strip_components: 2
