name: Deploy Hemi Webapp in prod

# Will limit one workflow at the same time
concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: false

on:
  release:
    types: [published]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Deploy claim-tokens microservice
        run: npx lerna run deploy --scope=claim-tokens
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CLAIM_WELCOME_PACK_ZAPIER_WEBHOOK_URL: ${{ secrets.CLAIM_WELCOME_PACK_ZAPIER_WEBHOOK_URL }}
          DEPLOY_POSTGRES_CONNECTION_DATABASE: ${{ secrets.POSTGRES_CONNECTION_DATABASE }}
          DEPLOY_POSTGRES_CONNECTION_HOST: ${{ secrets.POSTGRES_CONNECTION_HOST }}
          DEPLOY_POSTGRES_CONNECTION_PASSWORD: ${{ secrets.POSTGRES_CONNECTION_PASSWORD }}
          DEPLOY_POSTGRES_CONNECTION_USER: ${{ secrets.POSTGRES_CONNECTION_USER }}
          ENABLE_DUPLICATED_EMAIL_CHECK: true
          ENABLE_IP_CHECK: true
          HASH_SECRET_KEY: ${{ secrets.HASH_SECRET_KEY }}
          IP_QUALITY_SCORE_SECRET_KEY: ${{ secrets.IP_QUALITY_SCORE_SECRET_KEY }}
          PORTAL_DOMAIN_URL: https://app.hemi.xyz
          RECAPTCHA_SECRET_KEY: ${{ secrets.RECAPTCHA_SECRET_KEY_PROD }}
          STAGE: 'prod'

      - name: Deploy portal
        uses: ./.github/actions/deploy-portal
        with:
          # hostinger env variables
          HOSTINGER_HOST: ${{ secrets.HOSTINGER_HOST }}
          HOSTINGER_PORT: ${{ secrets.HOSTINGER_PORT }}
          HOSTINGER_SSH_KEY: ${{ secrets.HOSTINGER_SSH_KEY }}
          HOSTINGER_USER: ${{ secrets.HOSTINGER_USER }}
          HOSTINGER_TARGET: 'domains/hemi.xyz/public_html/app'
          # next env variables to build the portal
          NEXT_PUBLIC_CLAIM_TOKENS_URL: 'https://tf27a29m9d.execute-api.eu-central-1.amazonaws.com/prod'
          NEXT_PUBLIC_FEATURE_FLAG_ENABLE_BTC_TUNNEL: false
          NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${{ secrets.NEXT_PUBLIC_RECAPTCHA_SITE_KEY_PROD }}
